### ISSUE TITLE
MetaMask: "signing can have dangerous side effects"

### ISSUE THREAD

**Issue by freeatnet** [forkdelta/forkdelta.github.io#20]
MetaMask is currently displaying the following when the user attempts to sign an off-chain order:

> Signing this message can have dangerous side effects. Only sign messages from sites you fully trust with your entire account. This dangerous method will be removed in a future version. Read more [here](https://medium.com/metamask/the-new-secure-way-to-sign-data-in-your-browser-6af9dd2a1527).

**Comment by zaptrem** [comment]
This is an EtherDelta issue. Until they change the way they store their orders, I don't think there is much we can do about it.

**Comment by betterdelta** [comment]
Can't we switch from eth_sign to personal_sign without changing the signature that is generated for an input?

**Comment by betterdelta** [comment]
https://github.com/0xProject/0x-monorepo/issues/162 is an interesting read.

This actually looks worse than the current MetaMask warning.

**Comment by jamespic** [comment]
One advantage of switching to `personal_sign` is that it makes it possible to support RPC providers that don't support `eth_sign` but do support `personal_sign` (my interest in this is that I'm working on a browser plugin to support Ledger wallets, which don't support `eth_sign` by design - yes I know ForkDelta already supports Ledger).
